- name: Listen for RHEL Performance Co-Pilot events
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000

  rules:
    - name: Respond to PMIE rule cpu.util
      condition: event.payload.pcp.pmie.rule == "High average processor utilization"      
      action:
        run_playbook:
          name: playbooks/cpu.util.yml

    - name: Respond to PMIE rule memory.exhausted
      condition: event.payload.pcp.pmie.rule == "Severe demand for real memory"
      action:
        run_playbook:
          name: playbooks/memory.exhausted.yml

    - name: Respond to PMIE rule cpu.load_average
      condition: event.payload.pcp.pmie.rule == "High 1-minute load average"
      action:
        run_playbook:
          name: playbooks/cpu.load_average.yml

    - name: Respond to PMIE rule filesys.filling
      # Ansible cannot login to the managed node which is 100% full filesystem. 
      # Therefore, launch this rule only when the file system is not 100% full.
      condition: 
        all:
          #- event.payload.pcp.pmie.rule == "File system is filling up" 
          #- event.payload.pcp.pmie.message is not search("100%")
          #- "'100' not in event.payload.pcp.pmie.message"
          #- event.payload.pcp.pmie.message.find('100') == -1
          #- event.payload.pcp.pmie.message not contains 100
          #- event.payload.pcp.pmie.message is match("100",ignorecase=true)
          #- event.payload.pcp.pmie.message == '100'
          - "event.payload.pcp.pmie.message is not match('100%',ignorecase=true) and event.payload.pcp.pmie.rule == 'File system is filling up'" 
      action:
        run_playbook:
          name: playbooks/manage_filesystems/filesys.filling.yml

    - name: Launch PMIE rule filesys.filling when the managed node file system is 100% full
      # Ansible cannot login to the managed node which is 100% full filesystem. 
      # Therefore, launch this rule only when the file system is not 100% full.
      condition: 
        all:
          #- event.payload.pcp.pmie.rule == "File system is filling up" 
          #- event.payload.pcp.pmie.message is not search("100%")
          #- "'100' not in event.payload.pcp.pmie.message"
          #- event.payload.pcp.pmie.message.find('100') == -1
          #- event.payload.pcp.pmie.message not contains 100
          #- event.payload.pcp.pmie.message is match("100",ignorecase=true)
          #- event.payload.pcp.pmie.message == '100'
          - "event.payload.pcp.pmie.message is match('100%',ignorecase=true) and event.payload.pcp.pmie.rule == 'File system is filling up'" 
      action:
        run_playbook:
          name: playbooks/manage_filesystems/filesys.filling.yml

    - name:  Display any contents of event.payload variable
      condition: event.payload is defined
      action:
        debug:
          msg: "Received: {{ event.payload }}"


    #- name: Respond to PMIE rule cpu.context_switch
    #  condition: event.payload.pcp.pmie.rule == "High aggregate context switch rate"
    #  action:
    #    run_playbook:
    #      name: eda-test.yml
