- name: Listen for RHEL Performance Co-Pilot events
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000

  rules:
    - name: Respond to PMIE rule filesys.filling
      # Ansible cannot login to the managed node which is 100% full filesystem. 
      # Therefore, launch this rule only when the file system is not 100% full.
      condition: "event.payload.pcp.pmie.message is not match('100%',ignorecase=true) and event.payload.pcp.pmie.rule == 'File system is filling up'" 
      action:
        run_playbook:
          name: playbooks/manage_filesystems/filesys.filling.yml

    - name: Launch PMIE rule filesys.filling when the managed node file system is 100% full
      # Ansible cannot login to the managed node which is 100% full filesystem. 
      # Therefore, launch this rule only when the file system is not 100% full.
      condition: "event.payload.pcp.pmie.message is match('100%',ignorecase=true) and event.payload.pcp.pmie.rule == 'File system is filling up'" 
      action:
        run_playbook:
          name: playbooks/manage_filesystems/notify_filesystem_usage.yaml

    - name: Display any contents of event.payload variable
      condition: event.payload is defined
      action:
        debug:
          msg: "Received: {{ event.payload }}"