---
- name: EDA response to PMIE rule cpu.load_average
  hosts: "{{ ansible_eda.event.payload.pcp.pmie.hostname }}"
  become: true
  gather_facts: false #The managed node is in a low performance at the moment, avoid unnecessary tasks.
  tasks: 
    - ansible.builtin.include_vars: ./webex.yml

    - name: Display ansible_eda.event.payload.pcp.pmie.message variable
      debug:
        msg: "ansible_eda.event.payload.pcp.pmie.message value: {{ ansible_eda.event.payload.pcp.pmie.message }}"
   
    - name: Display ansible_eda.event.payload.pcp.pmie.rule variable
      debug:
        msg: "ansible_eda.event.payload.pcp.pmie.rule value: {{ ansible_eda.event.payload.pcp.pmie.rule }}"

    - name: df -h result before delete files
      command: df -h
      register: before_delete_files_df_result
    
    - name: Find files unused for 7 days
      command: find /tmp -type f -atime +7
      register: unused_files

    - name: Delete unused files for 7 days
      ansible.builtin.file:
        path: "{{ unused_files.stdout }}" #"{{ item }}"
        state: absent

    - name: df -h result after delete files
      command: df -h
      register: after_delete_files_df_result

    - name: Cisco Webex Teams - Text Message to a Room
      community.general.cisco_webex:
        recipient_type: roomId
        recipient_id: "{{ room_id }}"
        msg_type: markdown
        personal_token: "{{ token }}"
        msg: "{{ lookup('ansible.builtin.template', './templates/chatMsg.j2') }}"
        #"pcp `filesys.filling` rule has been launced from the managed host {{ ansible_eda.event.payload.pcp.pmie.hostname }}. Please check this host.\nHere is `df -h` result.\n{{ result.stdout }}"
