- name: Listen for RHEL Performance Co-Pilot events
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000

  rules:
    - name: Respond to PMIE rule cpu.util
      condition: event.payload.pcp.pmie.rule == "Low average processor utilization"       
      action:
        run_playbook:
          name: playbooks/LightSwitchOps/low_cpu_usage.yaml